### ISSUE TITLE
Plugin fails when there are files with unmodified paths

### ISSUE THREAD

**Issue by th0r** [sindresorhus/gulp-revert-path#1]
This task:

``` js
gulp.task('babel', () => {
    var babel = require('gulp-babel');
    var revertPath = require('gulp-revert-path');

    return gulp
        .src('**/*.{js,jsx}')
        .pipe(babel())
        .pipe(revertPath())
        .pipe(gulp.dest('dest'));
});
```

...fails with `Error: path should be string`. That's because `file.history` length is `1` for unmodified `*.js` files, but in the code `file.history.pop()` is used twice.

**Comment by th0r** [comment]
@sindresorhus Do you mind publishing this changes to npm?

**Comment by th0r** [comment]
@sindresorhus ping

**Comment by sindresorhus** [comment]
Done now. Sorry about the delay. I did publish initially, but looks some registry error failed it.

**Comment by th0r** [comment]
@sindresorhus Thanks!
